const SET_COMMENT_QUERY = 'SET_COMMENT_QUERY';
const SET_COMMENTS = 'SET_COMMENTS';
const SET_COMMENT_ERROR = 'SET_COMMENT_ERROR';
const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';
const FETCH_COMMENTS_BEGIN = 'FETCH_COMMENTS_BEGIN';
const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export default {
    SET_COMMENT_QUERY,
    SET_COMMENTS,
    SET_COMMENT_ERROR,
    REMOVE_COMMENT_ERROR,
    FETCH_COMMENTS_BEGIN,
    FETCH_COMMENTS_FAILURE,
    FETCH_COMMENTS_SUCCESS,
};
