export const SET_STACK_SEARCH_TERM = "SET_STACK_SEARCH_TERM";
export const SET_STACK_SORT_ORDER = "SET_STACK_SORT_ORDER";
export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
