export const SET_USERNAME = "SET_USERNAME";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const FETCH_REPOS_BEGIN = "FETCH_REPOS_BEGIN";
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";
