const SET_USER = 'SET_USER';
const SET_REPOS = 'SET_REPOS';
const SET_FORM_ERROR = 'SET_FORM_ERROR';
const SET_KEY_TO_EMPTY_STRING = 'SET_KEY_TO_EMPTY_STRING';
const FETCH_REPOS_BEGIN = 'FETCH_REPOS_BEGIN';
const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';

export default {
    SET_USER,
    SET_REPOS,
    SET_FORM_ERROR,
    SET_KEY_TO_EMPTY_STRING,
    FETCH_REPOS_BEGIN,
    FETCH_REPOS_FAILURE,
    FETCH_REPOS_SUCCESS,
};
