const SET_USERNAME = 'SET_USERNAME';
const SET_QUERY = 'SET_QUERY';
const GET_REPOS = 'GET_REPOS';
const SET_REPOS = 'SET_REPOS';
const SET_FILTER_QUERY = 'SET_FILTER_QUERY';
const SET_FILTERED_REPOS = 'SET_FILTERED_REPOS';

export default {
    SET_USERNAME,
    SET_QUERY,
    GET_REPOS,
    SET_REPOS,
    SET_FILTER_QUERY,
    SET_FILTERED_REPOS,
};
